"""Build Yappaflow_TR_Outreach_Leads_Additions_2026-04-28.xlsx — schema-mirror of the 2026-04-26 file.
Generated by scheduled task 'yappaflow-find-contacts'.
"""
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

NAVY = "FF1F3A5F"
WHITE = "FFFFFFFF"

ARIAL_TITLE   = Font(name="Arial", size=14, bold=True, color=WHITE)
ARIAL_TITLE_2 = Font(name="Arial", size=13, bold=True, color=WHITE)
ARIAL_SUB     = Font(name="Arial", size=10, bold=False)
ARIAL_H       = Font(name="Arial", size=11, bold=True)
ARIAL_BODY    = Font(name="Arial", size=10, bold=False)
ARIAL_HDR     = Font(name="Arial", size=10, bold=True, color=WHITE)

NAVY_FILL = PatternFill("solid", fgColor=NAVY)
CENTER_WRAP = Alignment(horizontal="center", vertical="center", wrap_text=True)
TOP_WRAP    = Alignment(horizontal="general", vertical="top", wrap_text=True)
LEFT_WRAP   = Alignment(horizontal="left", vertical="top", wrap_text=True)

# ---------- Data ----------
ROWS = [
    # (Company, Type, City, Website, Email, Phone, LinkedIn, Decision-maker, Fit, Angle, Priority)
    ("Deserve Studio", "Platform Partner", "Istanbul",
     "https://deserve.studio/", "audit@deserve.studio", "",
     "https://www.linkedin.com/company/deservestudio",
     "Enes Aktaş (Co-founder)",
     "Enterprise Framer Expert delivering SEO-optimized Framer sites for SaaS and startups — exact aesthetic Yappaflow generates by default.",
     "Client + Partnership", "High"),
    ("Mert Kahveci", "Freelancer", "Istanbul",
     "https://www.mertkahveci.com/", "", "",
     "https://www.linkedin.com/in/mert-kaan-kahveci-254511175/",
     "Mert Kahveci",
     "Solo Framer + product designer (SaaS-focused). Sells Framer templates (Lugo, Nucleum) — would 5x his throughput with Yappaflow.",
     "Client", "High"),
    ("Ahmet Köse", "Freelancer", "Istanbul",
     "https://www.ahmetkose.net/", "", "",
     "https://tr.linkedin.com/in/ahmet-kose",
     "Ahmet Köse",
     "Framer Expert & Partner shipping conversion-focused templates (Nolary, Astralis, Photon, VisaFlow). Active publisher — high X/Framer reach.",
     "Client", "High"),
    ("Agenzia", "Platform Partner", "Antalya",
     "https://agenzia.com.tr/", "", "",
     "",
     "",
     "Multi-platform partner: ikas + Ticimax + T-Soft + IdeaSoft + PlatinMarket. Antalya HQ — fills the gap of Turkish e-commerce platforms beyond ikas. Exactly the partner profile the BUILDER-PIVOT 'CMS adapter' angle was written for.",
     "Partnership", "High"),
    ("WooTurkey", "Platform Partner", "Turkey (national)",
     "https://www.wooturkey.com/", "eticaret@wooturkey.com", "",
     "",
     "",
     "WooCommerce specialist for Turkish market. Yappaflow doesn't ship a WooCommerce adapter today, but they're the natural beachhead the day we do — and a 'static marketing site + WooCommerce store' combo is a real funnel.",
     "Partnership", "Medium"),
    ("Studio Nord", "Agency", "Istanbul (Şişli)",
     "https://www.studionord.org/", "marvin@studionord.org", "+90 212 292 4095",
     "https://www.linkedin.com/company/studio-nord",
     "Gürkan Tümer (Founder)",
     "Award-winning dev/design studio, multi-platform digital experiences. Mid-tier shop where Yappaflow can quietly accelerate brief→draft.",
     "Client", "Medium"),
    ("Black Studio Agency", "Agency", "Istanbul (Şişli/Esentepe)",
     "https://blackstudio.agency/", "", "",
     "https://www.linkedin.com/company/black-studio-agency",
     "",
     "Branding + UX/UI + 3D/2D/NFT shop, founded 2019. Small team — productivity gain from Yappaflow lands immediately.",
     "Client", "Medium"),
    ("Baht Design Studio", "Agency", "Istanbul + London",
     "https://www.baht.design/", "", "",
     "",
     "",
     "Branding & visual communication studio, dual-city (Istanbul/London). Premium aesthetic — would showcase Yappaflow's light/dark theme story well.",
     "Client", "Medium"),
    ("Most Creative", "Agency", "Istanbul",
     "https://www.most.com.tr/", "", "",
     "",
     "",
     "Founded 2018, <10-person creative shop (branding + graphic + web). Fits the small-studio Yappaflow buyer profile from the Plan sheet.",
     "Client", "Medium"),
    ("Grifa", "Agency", "Istanbul (Kadıköy) + Tallinn",
     "https://www.grifa.com.tr/", "info@grifa.com.tr", "+90 850 346 5880",
     "",
     "",
     "Web + mobile + SEO since 2005. Two-office (TR/EE) — useful for Yappaflow's eventual EU expansion narrative. Still small enough to care about delivery speed.",
     "Client", "Medium"),
    ("Tercih Yazılım", "Agency", "Aydın",
     "https://www.tercihyazilim.com/", "info@tercihyazilim.com", "+90 544 293 04 16",
     "",
     "",
     "Aydın-based since 2011 — tier-2 city not present in main file. Corporate web + e-commerce + SEO. Classic 'small-business sites at volume' Yappaflow buyer.",
     "Client", "Medium"),
    ("Beyazgül GROUP", "Agency", "Tekirdağ (Süleymanpaşa)",
     "https://beyazgulgroup.com/", "", "+90 506 717 78 79",
     "https://www.linkedin.com/in/beyazgulgroup/",
     "",
     "Tekirdağ since 2012 — another tier-2 gap-fill. Works across web, software, e-commerce, healthcare verticals. Multi-vertical = lots of one-off site jobs.",
     "Client", "Medium"),
    ("Aydınweb", "Agency", "Aydın",
     "https://www.aydinweb.com.tr/", "", "",
     "",
     "",
     "Aydın-focused web design firm. Smaller shop — Yappaflow's 'first 5 sites free' offer is the right hook.",
     "Client", "Low"),
    ("WebAjansınız (W.B.A)", "Agency", "Malatya (national reach)",
     "https://webajansiniz.com.tr/", "", "",
     "",
     "",
     "Web + SEO + e-commerce, claims 81-province coverage. Volume-oriented — Yappaflow's pitch is 'one person delivers a small studio's volume'.",
     "Client", "Low"),
    ("Webolizma", "Agency", "Turkey (national)",
     "https://webolizma.com/", "", "",
     "",
     "",
     "Hız- & SEO-uyumlu web tasarım pitch — performance-first positioning aligns with Yappaflow's static + light-theme defaults.",
     "Client", "Low"),
]

CROSS = [
    # candidates considered today and rejected/duplicated
    ("Nodus Works", "Already in main file", "Duplicate"),
    ("Lein Digital", "Already in main file", "Duplicate"),
    ("Creamake", "Already in main file", "Duplicate"),
    ("Prix Studio", "Already in main file", "Duplicate"),
    ("Alis Dijital", "Already in main file", "Duplicate"),
    ("YCF Digital", "Already in main file", "Duplicate"),
    ("Asquared Agency", "Already in main file", "Duplicate"),
    ("Digital Pals", "Already in main file", "Duplicate"),
    ("PATH (Software House)", "Already in main file", "Duplicate"),
    ("Shopiuzman", "Already in main file", "Duplicate"),
    ("Artelio Creative", "Already in main file", "Duplicate"),
    ("Qreate Dijital", "Already in main file", "Duplicate"),
    ("Artnova Creative", "Already in main file", "Duplicate"),
    ("CreaTwins", "Already in main file", "Duplicate"),
    ("Ajans Max", "Already in main file", "Duplicate"),
    ("Mimoza Bilişim", "Already in main file", "Duplicate"),
    ("Penta Yazılım", "Already in main file", "Duplicate"),
    ("Yonkasoft", "Already in main file", "Duplicate"),
    ("OVARSA Yazılım", "Already in main file", "Duplicate"),
    ("CREAMIVE", "Already in main file", "Duplicate"),
    ("Manisaweb", "Already in main file", "Duplicate"),
    ("Mastertasarim", "Already in main file", "Duplicate"),
    ("Ceviz Bilişim", "Already in main file", "Duplicate"),
    ("Mudiweb", "Already in main file", "Duplicate"),
    ("WTS Web Tasarım Sistemleri", "Already in main file", "Duplicate"),
    ("Proji", "Already in main file", "Duplicate"),
    ("Marka Works", "Already in main file", "Duplicate"),
    ("432 Design Studio", "Already in main file", "Duplicate"),
    ("Starter Design", "Already in main file", "Duplicate"),
    ("Ait Istanbul", "Already in main file", "Duplicate"),
    ("UBF Branding", "Already in main file", "Duplicate"),
    ("Mustafa Ozalcin (Webflow)", "Already in 2026-04-26 additions", "Duplicate"),
    ("Compagram (Kayseri)", "Already in 2026-04-26 additions", "Duplicate"),
    ("Karen Dijital (Bursa)", "Already in 2026-04-26 additions", "Duplicate"),
    # rejected
    ("Flowtrix", "Already in main file (2026-04-25 additions)", "Duplicate"),
    ("CloseFuture", "Dropped — wrote a 'Top Framer agencies in Turkey' listicle but HQ outside Turkey unclear; cannot confirm Turkey presence", "Out of scope"),
    ("Fehmi (Framer dev)", "Dropped — no public website/contact found beyond Framer profile alias", "No reachable contact"),
    ("Kadir Can Tüfek", "Dropped — Lead Framer dev at Deserve Studio (already on this list); avoid double-touch", "Overlap"),
    ("MOB 34", "Dropped — could not confirm active company website (mob34.co not resolving)", "No reachable contact"),
    ("Studio Side", "Dropped — surfaced from Behance only, no agency site found", "No reachable contact"),
    ("Creatives Data", "Dropped — Istanbul tech/data/AI consultancy, not a website-building agency", "Out of scope"),
    ("WebStudio (ws.com.tr)", "Already in main file (Leads row 3)", "Duplicate"),
    ("Grimor Web Tasarım", "Already in main file (Leads row 1)", "Duplicate"),
    ("Kumsal Agency", "Already in main file (Leads row 2)", "Duplicate"),
]

# ---------- Build workbook ----------
wb = Workbook()

# === Plan sheet ===
plan = wb.active
plan.title = "Plan"
plan.column_dimensions["A"].width = 140

plan_rows = [
    ("title",   "Yappaflow — Turkish outreach leads · Additions for 2026-04-28"),
    ("sub",     "Automated supplement to Yappaflow_TR_Outreach_Leads.xlsx — generated by scheduled task 'yappaflow-find-contacts'."),
    ("blank",   ""),
    ("h",       "1. Why this file exists"),
    ("body",    "  • Scheduled task asked: \"find contacts around Turkey who can be interested in this project and add the excel file.\""),
    ("body",    "  • The user planned to send a file but could not — Claude found Yappaflow_TR_Outreach_Leads.xlsx (523 leads) + Yappaflow_TR_Outreach_Leads_Additions_2026-04-26.xlsx (18 net-new) already in /Yappaflow."),
    ("body",    "  • To avoid corrupting that work, this file is a SEPARATE supplement (third in the series). Merge into the main file after review."),
    ("blank",   ""),
    ("h",       "2. Selection rules used (2026-04-28)"),
    ("body",    "  • Cross-referenced every candidate against ALL existing 4 sheets in the main file + the 2026-04-26 additions + its 32-row Cross-check log. Entries below are NET-NEW only."),
    ("body",    "  • Targeted gaps the previous additions did not fill:"),
    ("body",    "      – Framer Experts (now Yappaflow's closest aesthetic peer) — 3 entries: Deserve Studio, Mert Kahveci, Ahmet Köse."),
    ("body",    "      – Multi-platform Turkish e-commerce partners beyond ikas (Ticimax / T-Soft / IdeaSoft) — Agenzia (Antalya), only such partner found that isn't already on the list."),
    ("body",    "      – WooCommerce-specialist partner (WooTurkey) — beachhead for the day Yappaflow ships a Woo adapter."),
    ("body",    "      – Tier-2 cities still light: Aydın (2 new), Tekirdağ (1 new), Malatya (1 new)."),
    ("body",    "      – Premium boutique design studios in Istanbul (Studio Nord, Black Studio, Baht, Most Creative) — small-team productivity buyers per the main Plan."),
    ("body",    "  • Schema matches the existing Leads sheet exactly (13 columns) so rows can be copy-pasted in."),
    ("body",    "  • Priority logic same as main file: High = warm fit (Framer/multi-platform partner), Medium = generalist mid-tier, Low = generalist regional."),
    ("blank",   ""),
    ("h",       "3. Verification status"),
    ("body",    "  • All 15 websites verified live during research on 2026-04-28."),
    ("body",    "  • Email/phone present where directly visible on the agency website or a directory listing (Studio Nord, Grifa, Tercih Yazılım, Beyazgül, Deserve Studio, WooTurkey)."),
    ("body",    "  • Where contact is blank — use the website contact form or LinkedIn DM as the first touch (consistent with main-file convention)."),
    ("blank",   ""),
    ("h",       "4. Recommended next actions for Yusuf Mirza"),
    ("body",    "  • Highest leverage: Deserve Studio + Ahmet Köse + Mert Kahveci. They already build the exact Framer-style sites Yappaflow generates — the demo lands on first contact."),
    ("body",    "  • Partnership angle: Agenzia (multi-platform Antalya partner) and WooTurkey (Woo specialist) — pitch the funnel-filler frame from the main Plan."),
    ("body",    "  • Review the Additions sheet, drop anything you don't want, then paste matching rows into Yappaflow_TR_Outreach_Leads.xlsx → Leads."),
    ("blank",   ""),
    ("h",       "5. Sources used"),
    ("body",    "  • Framer official Experts directory + framer.com/agencies."),
    ("body",    "  • Goodspeed Studio 'Top Framer Experts in Turkey' (2026)."),
    ("body",    "  • Turkish e-commerce comparison articles (Birkan Ulusoy, Olay Bu İşte, Eticaret Radarı) for ikas/Ticimax/T-Soft/IdeaSoft partner agencies."),
    ("body",    "  • Sortlist / Clutch / TechBehemoths / Manifest 2026 directory listings."),
    ("body",    "  • Direct agency websites (deserve.studio, mertkahveci.com, ahmetkose.net, agenzia.com.tr, studionord.org, grifa.com.tr, tercihyazilim.com, beyazgulgroup.com, blackstudio.agency, baht.design, wooturkey.com)."),
]

for i, (kind, text) in enumerate(plan_rows, start=1):
    if kind == "blank":
        continue
    cell = plan.cell(row=i, column=1, value=text)
    if kind == "title":
        cell.font = ARIAL_TITLE
        cell.fill = NAVY_FILL
        plan.row_dimensions[i].height = 24
    elif kind == "sub":
        cell.font = ARIAL_SUB
    elif kind == "h":
        cell.font = ARIAL_H
    else:  # body
        cell.font = Font(name="Arial", size=10)

# === Additions data sheet ===
ws = wb.create_sheet("Additions 2026-04-28")
ws.merge_cells("A1:M1")
c = ws.cell(row=1, column=1, value="Yappaflow — Turkey net-new leads (additions to main file)")
c.font = ARIAL_TITLE_2
c.fill = NAVY_FILL
c.alignment = Alignment(horizontal="left", vertical="center")
ws.row_dimensions[1].height = 22

ws.merge_cells("A2:M2")
c = ws.cell(row=2, column=1,
    value="Schema mirrors Yappaflow_TR_Outreach_Leads.xlsx → Leads sheet (13 columns). 15 net-new entries · cross-checked against 523 existing leads + the 2026-04-26 additions log.")
c.font = ARIAL_SUB

# Headers row 4
HEADERS = ["#", "Company / Name", "Type", "City", "Website", "Email", "Phone",
           "LinkedIn", "Decision-maker", "Fit note", "Outreach angle", "Priority", "Status"]
for j, h in enumerate(HEADERS, start=1):
    c = ws.cell(row=4, column=j, value=h)
    c.font = ARIAL_HDR
    c.fill = NAVY_FILL
    c.alignment = CENTER_WRAP
ws.row_dimensions[4].height = 30

# Body
for i, row in enumerate(ROWS, start=1):
    excel_row = 4 + i
    # Spread tuple: (Company, Type, City, Website, Email, Phone, LinkedIn, DM, Fit, Angle, Priority)
    values = [i] + list(row) + [""]  # status blank
    for j, v in enumerate(values, start=1):
        c = ws.cell(row=excel_row, column=j, value=v)
        c.font = ARIAL_BODY
        c.alignment = TOP_WRAP

# Column widths matching prior file
widths = {"A":5, "B":32, "C":18, "D":24, "E":36, "F":28, "G":20, "H":36, "I":24, "J":62, "K":18, "L":11, "M":12}
for col, w in widths.items():
    ws.column_dimensions[col].width = w

ws.freeze_panes = "A5"

# === Cross-check log sheet ===
log = wb.create_sheet("Cross-check log")
log_headers = ["Candidate considered", "Result", "Reason"]
for j, h in enumerate(log_headers, start=1):
    c = log.cell(row=1, column=j, value=h)
    c.font = ARIAL_HDR
    c.fill = NAVY_FILL
    c.alignment = CENTER_WRAP
log.row_dimensions[1].height = 24
for i, row in enumerate(CROSS, start=1):
    for j, v in enumerate(row, start=1):
        c = log.cell(row=i+1, column=j, value=v)
        c.font = ARIAL_BODY
        c.alignment = TOP_WRAP
log.column_dimensions["A"].width = 32
log.column_dimensions["B"].width = 60
log.column_dimensions["C"].width = 20
log.freeze_panes = "A2"

out = "/sessions/nifty-modest-archimedes/mnt/Yappaflow/Yappaflow_TR_Outreach_Leads_Additions_2026-04-28.xlsx"
wb.save(out)
print("Saved:", out)

# Quick verify
from openpyxl import load_workbook
wb2 = load_workbook(out)
print("Sheets:", wb2.sheetnames)
ws = wb2["Additions 2026-04-28"]
print(f"Data rows: {ws.max_row - 4} / cols: {ws.max_column}")
log = wb2["Cross-check log"]
print(f"Log rows: {log.max_row - 1}")
