import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { expressMiddleware } from "@as-integrations/express5";
import { createApolloServer } from "./graphql";
import { connectDatabase } from "./config/db";
import { env } from "./config/env";
import { log } from "./utils/logger";
import { buildAuthContext } from "./middleware/auth";
import { isMockMode } from "./ai/client";
import instagramRouter from "./routes/instagram.route";
import shopifyRouter         from "./routes/shopify.route";
import shopifyWebhooksRouter from "./routes/shopify-webhooks.route";
import webflowRouter         from "./routes/webflow.route";
import webflowWebhooksRouter from "./routes/webflow-webhooks.route";
import wordpressRouter          from "./routes/wordpress.route";
import wordpressWebhooksRouter  from "./routes/wordpress-webhooks.route";
import ikasRouter              from "./routes/ikas.route";
import ikasWebhooksRouter      from "./routes/ikas-webhooks.route";
import webhooksRouter  from "./routes/webhooks.route";
import sseRouter       from "./routes/sse.route";
import aiStreamRouter  from "./routes/ai-stream.route";
import aiDebugRouter   from "./routes/ai-debug.route";
import chatImportRouter from "./routes/chat-import.route";
import deployRouter      from "./routes/deploy.route";
import authSessionRouter from "./routes/auth-session.route";

// ── Allow-list for cross-origin callers ──────────────────────────────────────
// Exact-match origins. Add production/preview URLs here as we spin them up.
// Supports a comma-separated EXTRA_ALLOWED_ORIGINS env var so we can whitelist
// a new preview URL without a code change/redeploy.
const extraOrigins = (process.env.EXTRA_ALLOWED_ORIGINS ?? "")
  .split(",")
  .map((o) => o.trim())
  .filter(Boolean);

const allowedOrigins = [
  env.frontendUrl,
  "http://localhost:3000",
  "http://localhost:3001",
  "http://localhost:3002",
  "https://yappaflow.com",
  "https://www.yappaflow.com",
  "https://yappaflow.app",
  "https://www.yappaflow.app",
  ...extraOrigins,
];

// Pattern-match origins for platforms that hand out per-deployment subdomains
// (preview URLs, prod URLs auto-generated by the host). Safer than a blanket
// "*" because the match is scoped to known hosts.
const allowedOriginPatterns: RegExp[] = [
  /^https:\/\/[a-z0-9-]+\.vercel\.app$/i,       // Vercel preview + prod deploys
  /^https:\/\/[a-z0-9-]+\.up\.railway\.app$/i,  // Railway deploys
  /^https:\/\/[a-z0-9-]+\.railway\.app$/i,
  /^https:\/\/[a-z0-9-]+\.netlify\.app$/i,      // Netlify deploys
];

function isAllowedOrigin(origin: string): boolean {
  if (allowedOrigins.includes(origin)) return true;
  return allowedOriginPatterns.some((rx) => rx.test(origin));
}

const corsOptions: cors.CorsOptions = {
  /**
   * Per-origin gate for the `cors` middleware.
   *
   * IMPORTANT: we NEVER `callback(new Error(...))` on unknown origins.
   * Throwing from this callback bubbles up through Express's error
   * pipeline and — behind Railway's edge proxy — surfaces in the browser
   * as a confusing HTTP 400 on endpoints the backend never actually saw
   * (no log line, no handler invocation). Instead, callback(null, false):
   * the response simply won't carry CORS headers, the browser blocks it
   * on its own, server logs stay quiet, and our route handlers aren't
   * invoked with a weird origin.
   */
  origin: (origin, callback) => {
    // No Origin header → not a browser cross-origin request (mobile apps,
    // curl, server-to-server, same-origin fetches). Allow through.
    // Skip CORS headers in prod where the server is behind a proxy.
    if (!origin) return callback(null, env.nodeEnv !== "production");

    if (isAllowedOrigin(origin)) return callback(null, true);

    // Dev-only: permit ngrok tunnels so we can test webhooks locally.
    if (env.nodeEnv !== "production" && (origin.includes(".ngrok-free.dev") || origin.includes(".ngrok.io"))) {
      return callback(null, true);
    }

    // Unknown origin — deny silently (no thrown error, no CORS headers).
    // Logged once per request so we can spot legitimate new origins that
    // need whitelisting via EXTRA_ALLOWED_ORIGINS or the list above.
    log(`[CORS] blocked origin: ${origin}`);
    return callback(null, false);
  },
  credentials: true,
};

async function main() {
  const app = express();

  // ── Trust the platform proxy in production (Railway, Vercel, Fly, …) ───────
  // Railway terminates TLS at its edge and forwards to us over HTTP with
  // `X-Forwarded-For` set. Express defaults to `trust proxy = false` for
  // safety — which makes express-rate-limit refuse to use the forwarded IP
  // and throw `ERR_ERL_UNEXPECTED_X_FORWARDED_FOR` on every request.
  //
  // Setting `trust proxy = 1` tells Express to trust EXACTLY one hop (the
  // Railway ingress). Don't use `true` — that trusts any client-supplied
  // `X-Forwarded-For`, letting anyone spoof their IP past the rate limiter.
  //
  // Dev (NODE_ENV !== "production") talks to us directly, so we don't trust
  // any proxy — the default (0) is correct there.
  if (env.nodeEnv === "production") {
    app.set("trust proxy", 1);
  }

  // ── Security hardening ─────────────────────────────────────────────────────
  app.use(helmet({ contentSecurityPolicy: false })); // CSP off for GraphQL playground
  app.use(cookieParser());

  // Rate limiters
  const apiLimiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 100,                  // 100 requests per window per IP
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: "Too many requests — please try again later" },
  });
  const uploadLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 20,                    // 20 file uploads per 15 min
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: "Too many uploads — please try again later" },
  });
  const authLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 30,                    // 30 auth attempts per 15 min
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: "Too many login attempts — please try again later" },
  });
  const deployLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 1200,                  // generous — the project-state endpoint is polled during builds
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: "Too many deploy requests — please try again later" },
  });

  // Warn on insecure defaults
  if (env.jwtSecret === "dev-secret-change-in-production" || env.jwtSecret === "your-super-secret-jwt-key-change-this") {
    log("\n⚠️  WARNING: JWT_SECRET is a default placeholder — set a random 256-bit key in .env for production!");
    log("   Generate one: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"\n");
  }
  if (!env.encryptionMasterKey) {
    log("⚠️  WARNING: ENCRYPTION_MASTER_KEY is not set — chat messages will be stored in PLAINTEXT.");
    log("   Generate one: node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"\n");
  }

  await connectDatabase();

  app.use("/auth",    cors(corsOptions), authLimiter, express.json(), instagramRouter);
  app.use("/auth",    cors(corsOptions), authLimiter, express.json(), shopifyRouter);
  // Webflow OAuth + push live on the same router; auth endpoints end up at
  // `/auth/webflow/*` and the push endpoint at `/auth/webflow/push`. We
  // deliberately keep the dashboard → server call under `/auth` to reuse the
  // same CORS + rate-limit + JSON-parsing middleware chain as Shopify.
  app.use("/auth",    cors(corsOptions), authLimiter, express.json(), webflowRouter);
  // WordPress OAuth (WP.com) + self-hosted Application Password connect +
  // push endpoint — all mounted under /auth so they share the same CORS +
  // rate-limit + JSON chain as the other platform integrations.
  app.use("/auth",    cors(corsOptions), authLimiter, express.json(), wordpressRouter);
  // ikas OAuth + push — the push endpoint is /auth/ikas/push so we reuse the
  // same CORS + rate-limit + JSON chain as the other platform integrations.
  app.use("/auth",    cors(corsOptions), authLimiter, express.json(), ikasRouter);
  app.use("/auth",    cors(corsOptions), authLimiter, express.json(), authSessionRouter);
  // Shopify webhooks MUST receive the raw body bytes (HMAC is computed over
  // them exactly). Mount before `/webhook` + express.json() so nothing parses
  // the body first.
  app.use(
    "/webhook/shopify",
    express.raw({ type: "application/json", limit: "2mb" }),
    shopifyWebhooksRouter
  );
  // Webflow webhooks — same raw-body rule (signature is over the exact bytes).
  app.use(
    "/webhook/webflow",
    express.raw({ type: "application/json", limit: "2mb" }),
    webflowWebhooksRouter
  );
  // WordPress webhooks + maintenance endpoints. WP.com's deauthorize callback
  // is form-encoded (the router opts into urlencoded itself), and the
  // first-party /disconnect endpoint expects JSON — so use the normal JSON
  // parser here instead of raw bytes.
  app.use("/webhook/wordpress", express.json(), wordpressWebhooksRouter);
  // ikas webhooks — same raw-body rule (HMAC is over the exact body bytes).
  app.use(
    "/webhook/ikas",
    express.raw({ type: "application/json", limit: "2mb" }),
    ikasWebhooksRouter
  );
  app.use("/webhook", express.json(), webhooksRouter); // no CORS — server-to-server from Meta; no rate limit — Meta sends bursts
  app.use("/events",  cors(corsOptions), sseRouter);
  app.use("/ai",      cors(corsOptions), apiLimiter, express.json(), aiStreamRouter);
  app.use("/ai/debug", cors(corsOptions), express.json(), aiDebugRouter);
  app.use("/import",   cors(corsOptions), uploadLimiter, chatImportRouter); // multer handles its own body parsing
  app.use("/deploy",   cors(corsOptions), deployLimiter, express.json(), deployRouter);

  const apolloServer = createApolloServer();
  await apolloServer.start();

  // Apollo Server v4 with Express 4/5 — cors + json must be inline per route
  app.use(
    "/graphql",
    cors(corsOptions),
    express.json(),
    expressMiddleware(apolloServer, { context: buildAuthContext }) as unknown as express.RequestHandler
  );

  app.get("/health", (_req, res) => {
    res.json({ status: "ok", timestamp: new Date().toISOString() });
  });

  app.listen(env.port, () => {
    const base = `http://localhost:${env.port}`;
    log(`\n🚀 Server running at ${base}`);
    log(`   GraphQL        → ${base}/graphql`);
    log(`   Instagram OAuth→ ${base}/auth/instagram/authorize`);
    log(`   Shopify OAuth  → ${base}/auth/shopify/authorize?shop=<shop>.myshopify.com`);
    log(`   Webflow OAuth  → ${base}/auth/webflow/authorize`);
    log(`   WordPress (self-hosted) → POST ${base}/auth/wordpress/connect-application-password`);
    log(`   WordPress.com OAuth     → ${base}/auth/wordpress/authorize`);
    log(`   ikas OAuth     → ${base}/auth/ikas/authorize?store=<name>   (opens <name>.myikas.com)`);
    log(`\n📡 Webhook endpoints:`);
    log(`   Meta Cloud API → POST ${base}/webhook`);
    log(`      Verify token: ${env.metaWebhookVerifyToken}`);
    log(`      Register at: https://developers.facebook.com/apps → Webhooks`);
    log(`   Twilio WA      → POST ${base}/webhook/twilio`);
    log(`      Register at: https://console.twilio.com → Messaging → WhatsApp → Sandbox Settings`);
    log(`      "When a message comes in" → <your-ngrok-url>/webhook/twilio`);
    log(`   Shopify        → POST ${base}/webhook/shopify/app/uninstalled`);
    log(`                     POST ${base}/webhook/shopify/customers/data-request`);
    log(`                     POST ${base}/webhook/shopify/customers/redact`);
    log(`                     POST ${base}/webhook/shopify/shop/redact`);
    log(`      Register at: https://partners.shopify.com → your app → App setup → GDPR mandatory webhooks`);
    log(`   Webflow        → POST ${base}/webhook/webflow/site-publish`);
    log(`                     POST ${base}/webhook/webflow/app-uninstalled`);
    log(`                     POST ${base}/webhook/webflow/ecomm-new-order`);
    log(`      Register at: https://webflow.com → Workspace → Apps & integrations → your app → Webhooks`);
    log(`   WordPress      → POST ${base}/webhook/wordpress/deauthorize   (optional — WP.com apps only)`);
    log(`                     POST ${base}/webhook/wordpress/disconnect    (first-party: Yappaflow frontend)`);
    log(`                     GET  ${base}/webhook/wordpress/heartbeat`);
    log(`   ikas           → POST ${base}/webhook/ikas/app-uninstalled`);
    log(`                     POST ${base}/webhook/ikas/order-created`);
    log(`                     POST ${base}/webhook/ikas/product-updated`);
    log(`                     GET  ${base}/webhook/ikas/heartbeat`);
    log(`      Register at: https://ikas.dev → your app → Webhooks`);
    log(`   Debug (dev)    → POST ${base}/webhook/debug`);
    log(`      curl -X POST ${base}/webhook/debug \\`);
    log(`           -H "Content-Type: application/json" \\`);
    log(`           -d '{"phone":"+905551234567","name":"Test","message":"Hello"}'`);
    log(`\n🤖 AI Engine:`);
    if (isMockMode()) {
      log(`   Mode: MOCK (no API key — using sample data)`);
      log(`   Set ANTHROPIC_API_KEY in .env for real AI responses`);
    } else {
      log(`   Mode: LIVE (${env.anthropicModel})`);
    }
    log(`   Stream     → GET ${base}/ai/stream/:sessionId`);
    log(`\n🧪 AI Debug (dev only — no auth needed):`);
    log(`   Test analyze → curl -X POST ${base}/ai/debug/test -H "Content-Type: application/json" -d '{"scenario":"fashion-ecommerce","mode":"analyze"}'`);
    log(`   Test full    → curl -X POST ${base}/ai/debug/test -H "Content-Type: application/json" -d '{"scenario":"tech-startup","mode":"full"}'`);
    log(`   Sessions    → GET ${base}/ai/debug/sessions`);
    log(`   Cleanup     → DELETE ${base}/ai/debug/cleanup`);
    log(`   Scenarios: fashion-ecommerce, restaurant, tech-startup`);
    log(`\n💡 For local testing, expose this server with:`);
    log(`   npx ngrok http ${env.port}`);
    log(`   Then use the ngrok URL for webhook registration.\n`);
  });
}

main().catch(console.error);
