/**
 * Shopify "one-click import" bundle generator — scaffold-first edition.
 *
 * Yappaflow used to ask the AI to produce a full Shopify 2.0 theme from
 * scratch on every build: ~17 Liquid/JSON/CSS/JS files in a single
 * 32k-token generation, wrapped in a self-critique retry loop against a
 * Liquid validator. That worked but was expensive (tokens + wall-clock)
 * and fragile — a single dropped closing fence or missing `snippets/`
 * file would sink the whole bundle.
 *
 * The pipeline is now split in two cleanly-separated layers:
 *
 *   1. **Scaffold layer (static).** A complete, audited Shopify theme
 *      lives at `server/scaffolds/shopify-base/`: header, footer, cart,
 *      product page, collection, search, customer accounts, 404, the
 *      lot. The CSS is brand-agnostic and reads from CSS custom
 *      properties. Every file in the scaffold is copied verbatim into
 *      the generated bundle.
 *
 *   2. **Brand layer (AI).** A single narrow prompt emits one JSON
 *      object with design tokens, a small `brand.css`, and homepage
 *      section settings. That JSON is merged into the scaffold's
 *      `config/settings_data.json` plus written out as
 *      `assets/brand.css`. No Liquid is ever generated by the AI.
 *
 * Additional deterministic steps done server-side, NOT by the AI:
 *
 *   • Static product fallback. `sections/featured-products.liquid`
 *     ships with a hybrid render path: loop `collection.products` if
 *     present, else render static blocks. The blocks are written into
 *     `settings_data.json` here, one per entry in
 *     `Project.identity.products`. That way the ZIP preview (before
 *     the merchant imports products.csv) already shows the right
 *     product cards — fixing the "products not visible in generated
 *     theme" bug.
 *
 *   • `products.csv`. Built deterministically from
 *     `Project.identity.products`, not touched by the AI.
 *
 *   • `README.txt`. Top-level one-click upload instructions.
 *
 * The legacy Liquid validator / snippet-fallback / patch-regen loop is
 * retired — the scaffold is the "validator" now. All that remains to
 * validate at build time is the brand JSON itself (all required keys
 * present, colors parse, fonts are stacks).
 */

import fs from "node:fs/promises";
import path from "node:path";

import { Project, IProjectIdentity, IProduct, type IHeroChooser, type IHeroVariant } from "../models/Project.model";
import { GeneratedArtifact } from "../models/GeneratedArtifact.model";
import { AISession } from "../models/AISession.model";
import { analyzeOnce, trackUsage } from "./ai-client.service";
import {
  getGenerateShopifyBrandPrompt,
  getPatchShopifyBrandPrompt,
  type ShopifyProductForPrompt,
  type PatchShopifyBrandIssue,
} from "../ai/prompts/generate-shopify.prompt";
import { pickDesignDirection } from "../ai/design-directions";
import { log, logError } from "../utils/logger";

/* ------------------------------------------------------------------ *
 * Scaffold location                                                   *
 *                                                                     *
 * The scaffold is shipped alongside source as raw files (not bundled  *
 * into the JS output), so the path is relative to this compiled file. *
 * From `dist/services/shopify-generator.service.js` the scaffold sits *
 * at `../../scaffolds/shopify-base`. From the TS source path the same *
 * layout applies (tsc outputs `dist/services/...`).                   *
 * ------------------------------------------------------------------ */

const SCAFFOLD_DIR = path.resolve(__dirname, "..", "..", "scaffolds", "shopify-base");

/* ------------------------------------------------------------------ *
 * Helpers                                                             *
 * ------------------------------------------------------------------ */

const LANG_BY_EXT: Record<string, string> = {
  ".liquid": "liquid",
  ".json":   "json",
  ".css":    "css",
  ".js":     "javascript",
  ".csv":    "csv",
  ".svg":    "svg",
  ".md":     "markdown",
  ".txt":    "text",
};

function languageForPath(p: string): string {
  const idx = p.lastIndexOf(".");
  if (idx === -1) return "text";
  return LANG_BY_EXT[p.slice(idx).toLowerCase()] ?? "text";
}

/** Lower-case, dash-separated, ASCII-only handle (the Shopify "handle" rule). */
function toHandle(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "product";
}

function csvEscape(value: string | number | undefined | null): string {
  if (value === null || value === undefined) return "";
  const s = String(value);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

/* ------------------------------------------------------------------ *
 * Shopify CSV import                                                  *
 *                                                                     *
 * Column set is the minimal subset the Admin importer accepts cleanly *
 * while preserving variants and images.                               *
 * Ref: https://help.shopify.com/en/manual/products/import-export/using-csv
 * ------------------------------------------------------------------ */

const SHOPIFY_CSV_COLUMNS = [
  "Handle", "Title", "Body (HTML)", "Vendor", "Type", "Tags", "Published",
  "Option1 Name", "Option1 Value",
  "Variant SKU", "Variant Inventory Tracker", "Variant Inventory Qty",
  "Variant Inventory Policy", "Variant Fulfillment Service",
  "Variant Price", "Variant Requires Shipping", "Variant Taxable",
  "Image Src", "Image Position", "Image Alt Text", "Status",
] as const;

export function buildProductsCsv(
  identity: IProjectIdentity,
  products: IProduct[]
): string {
  const vendor = identity.businessName;
  const rows: string[] = [SHOPIFY_CSV_COLUMNS.join(",")];

  for (const p of products) {
    const handle = toHandle(p.name);
    const variants = p.variants?.length ? p.variants : [{ label: "Default Title" }];
    const optionName = p.variantKind
      ? p.variantKind[0].toUpperCase() + p.variantKind.slice(1)
      : "Title";
    const images = p.images?.length ? p.images : [];

    variants.forEach((variant, vIdx) => {
      const isFirst = vIdx === 0;
      const row: Record<typeof SHOPIFY_CSV_COLUMNS[number], string | number> = {
        "Handle":                      handle,
        "Title":                       isFirst ? p.name : "",
        "Body (HTML)":                 isFirst && p.description ? `<p>${p.description}</p>` : "",
        "Vendor":                      isFirst ? vendor : "",
        "Type":                        isFirst ? (identity.industry ?? "") : "",
        "Tags":                        isFirst ? (identity.industry ?? "") : "",
        "Published":                   isFirst ? "TRUE" : "",
        "Option1 Name":                isFirst ? optionName : "",
        "Option1 Value":               variant.label,
        "Variant SKU":                 variant.sku ?? `${handle}-${toHandle(variant.label)}`,
        "Variant Inventory Tracker":   "shopify",
        "Variant Inventory Qty":       100,
        "Variant Inventory Policy":    "deny",
        "Variant Fulfillment Service": "manual",
        "Variant Price":               Number((variant.price ?? p.price).toFixed(2)),
        "Variant Requires Shipping":   "TRUE",
        "Variant Taxable":             "TRUE",
        "Image Src":                   isFirst && images[0] ? images[0] : "",
        "Image Position":              isFirst && images[0] ? 1 : "",
        "Image Alt Text":              isFirst && images[0] ? p.name : "",
        "Status":                      isFirst ? "active" : "",
      };
      rows.push(SHOPIFY_CSV_COLUMNS.map((col) => csvEscape(row[col])).join(","));
    });

    if (images.length > 1) {
      for (let i = 1; i < images.length; i++) {
        const row: Record<typeof SHOPIFY_CSV_COLUMNS[number], string | number> = {
          "Handle":                      handle,
          "Title":                       "",
          "Body (HTML)":                 "",
          "Vendor":                      "",
          "Type":                        "",
          "Tags":                        "",
          "Published":                   "",
          "Option1 Name":                "",
          "Option1 Value":               "",
          "Variant SKU":                 "",
          "Variant Inventory Tracker":   "",
          "Variant Inventory Qty":       "",
          "Variant Inventory Policy":    "",
          "Variant Fulfillment Service": "",
          "Variant Price":               "",
          "Variant Requires Shipping":   "",
          "Variant Taxable":             "",
          "Image Src":                   images[i],
          "Image Position":              i + 1,
          "Image Alt Text":              p.name,
          "Status":                      "",
        };
        rows.push(SHOPIFY_CSV_COLUMNS.map((col) => csvEscape(row[col])).join(","));
      }
    }
  }

  return rows.join("\n") + "\n";
}

function productsForPrompt(identity: IProjectIdentity): ShopifyProductForPrompt[] {
  if (!identity.products?.length) return [];
  return identity.products.map((p) => ({
    handle:      toHandle(p.name),
    name:        p.name,
    price:       p.price,
    currency:    p.currency,
    description: p.description,
    variantKind: p.variantKind,
    variants:    p.variants?.map((v) => ({ label: v.label, price: v.price })),
  }));
}

/* ------------------------------------------------------------------ *
 * Scaffold loader                                                     *
 *                                                                     *
 * Walks SCAFFOLD_DIR and produces `{ filePath, content }[]` with      *
 * forward-slash paths (the scaffold lives on disk, but the generator  *
 * artifacts always use POSIX-style paths for ZIP portability).        *
 * ------------------------------------------------------------------ */

interface ScaffoldFile {
  filePath: string;   // relative POSIX path within theme/
  content:  string;
  language: string;
}

async function loadScaffold(): Promise<ScaffoldFile[]> {
  const files: ScaffoldFile[] = [];

  async function walk(dir: string, rel: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      // Skip the scaffold's own README — internal docs, not part of the
      // delivered theme.
      if (rel === "" && entry.name === "README.md") continue;

      const absPath = path.join(dir, entry.name);
      const relPath = rel ? `${rel}/${entry.name}` : entry.name;

      if (entry.isDirectory()) {
        await walk(absPath, relPath);
      } else if (entry.isFile()) {
        const content = await fs.readFile(absPath, "utf8");
        files.push({
          filePath: relPath,
          content,
          language: languageForPath(relPath),
        });
      }
    }
  }

  await walk(SCAFFOLD_DIR, "");
  return files;
}

/* ------------------------------------------------------------------ *
 * Brand JSON types + parsing                                          *
 * ------------------------------------------------------------------ */

const TOKEN_COLOR_KEYS = [
  "color_bg", "color_fg", "color_primary", "color_on_primary",
  "color_surface", "color_muted", "color_border", "color_accent",
  "color_bg_dark", "color_fg_dark", "color_primary_dark", "color_on_primary_dark",
  "color_surface_dark", "color_muted_dark", "color_border_dark", "color_accent_dark",
] as const;

type TokenColorKey = typeof TOKEN_COLOR_KEYS[number];

interface BrandJson {
  tokens: Record<TokenColorKey, string> & {
    font_display_family: string;
    font_body_family:    string;
  };
  brand_name:    string;
  brand_tagline: string;
  brand_css:     string;
  hero: {
    eyebrow:    string;
    headline:   string;
    subhead:    string;
    cta_label:  string;
    cta_link:   string;
    cta2_label: string;
    cta2_link:  string;
  };
  sections: {
    feature_grid?: {
      heading: string; subheading?: string;
      blocks: Array<{ icon?: string; heading: string; body: string }>;
    };
    testimonials?: {
      heading: string; subheading?: string;
      blocks: Array<{ quote: string; author: string; role?: string }>;
    };
    faq?: {
      heading: string; subheading?: string;
      blocks: Array<{ question: string; answer: string }>;
    };
    cta?: {
      heading: string; subhead?: string;
      cta_label: string; cta_link: string;
    };
    featured_products?: {
      heading?: string; subheading?: string;
      cta_label?: string; cta_link?: string;
    };
  };
  content_for_index: string[];
}

const HEX_RE = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

function stripJsonFences(s: string): string {
  // Some models wrap JSON in markdown fences despite instructions.
  // Strip ```json / ``` at the boundaries, then trim.
  return s
    .trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
}

function tryParseBrandJson(raw: string): { ok: true; value: BrandJson } | { ok: false; error: string } {
  try {
    const parsed = JSON.parse(stripJsonFences(raw));
    return { ok: true, value: parsed as BrandJson };
  } catch (err) {
    return { ok: false, error: (err as Error).message };
  }
}

function validateBrandJson(j: BrandJson | undefined | null): PatchShopifyBrandIssue[] {
  const issues: PatchShopifyBrandIssue[] = [];
  if (!j || typeof j !== "object") {
    issues.push({ path: "(root)", issue: "Output was not a JSON object" });
    return issues;
  }

  // tokens
  if (!j.tokens || typeof j.tokens !== "object") {
    issues.push({ path: "tokens", issue: "Missing tokens object" });
  } else {
    for (const k of TOKEN_COLOR_KEYS) {
      const v = j.tokens[k];
      if (typeof v !== "string" || !HEX_RE.test(v)) {
        issues.push({
          path:    `tokens.${k}`,
          issue:   `Missing or invalid hex color: ${v ?? "(missing)"}`,
          suggest: "Use #rrggbb format (e.g. #0a0a0a)",
        });
      }
    }
    for (const k of ["font_display_family", "font_body_family"] as const) {
      const v = j.tokens[k];
      if (typeof v !== "string" || v.trim().length < 3) {
        issues.push({ path: `tokens.${k}`, issue: "Missing font-family stack" });
      }
    }
  }

  // brand name + tagline
  if (typeof j.brand_name !== "string" || j.brand_name.trim() === "") {
    issues.push({ path: "brand_name", issue: "Missing brand_name" });
  }
  if (typeof j.brand_tagline !== "string") {
    issues.push({ path: "brand_tagline", issue: "Missing brand_tagline (can be empty string, not missing key)" });
  }

  // brand_css
  if (typeof j.brand_css !== "string") {
    issues.push({ path: "brand_css", issue: "Missing brand_css string" });
  }

  // hero
  if (!j.hero || typeof j.hero !== "object") {
    issues.push({ path: "hero", issue: "Missing hero object" });
  } else {
    for (const k of ["headline", "subhead", "cta_label", "cta_link"] as const) {
      if (typeof j.hero[k] !== "string" || j.hero[k].trim() === "") {
        issues.push({ path: `hero.${k}`, issue: `Missing hero.${k}` });
      }
    }
  }

  // sections (depth floors)
  const s = j.sections ?? {};
  if (!s.feature_grid || !Array.isArray(s.feature_grid.blocks) || s.feature_grid.blocks.length < 3) {
    issues.push({
      path:    "sections.feature_grid.blocks",
      issue:   "feature_grid needs at least 3 blocks (scaffold preset is 4)",
      suggest: "Return 4 feature blocks",
    });
  }
  if (!s.testimonials || !Array.isArray(s.testimonials.blocks) || s.testimonials.blocks.length < 2) {
    issues.push({ path: "sections.testimonials.blocks", issue: "testimonials needs at least 2 blocks" });
  }
  if (!s.faq || !Array.isArray(s.faq.blocks) || s.faq.blocks.length < 3) {
    issues.push({ path: "sections.faq.blocks", issue: "faq needs at least 3 blocks" });
  }
  if (!s.cta || typeof s.cta.heading !== "string") {
    issues.push({ path: "sections.cta.heading", issue: "Missing cta.heading" });
  }

  // content_for_index
  if (!Array.isArray(j.content_for_index) || j.content_for_index.length < 3) {
    issues.push({ path: "content_for_index", issue: "Need at least 3 section ids in content_for_index" });
  }

  return issues;
}

/* ------------------------------------------------------------------ *
 * Merge brand JSON into scaffold                                      *
 * ------------------------------------------------------------------ */

/**
 * Deep-merge the brand-layer JSON into the scaffold's
 * `config/settings_data.json`, overwrite `assets/brand.css`, and inject
 * static_product fallback blocks into the featured-products section.
 *
 * Returns a NEW scaffold file array — input is not mutated.
 */
function applyBrandLayer(
  scaffold: ScaffoldFile[],
  brand: BrandJson,
  identity: IProjectIdentity,
): ScaffoldFile[] {
  const byPath = new Map(scaffold.map((f) => [f.filePath, { ...f }] as const));

  // settings_data.json
  const sdPath = "config/settings_data.json";
  const sdFile = byPath.get(sdPath);
  if (!sdFile) throw new Error(`Scaffold missing ${sdPath}`);

  const sd = JSON.parse(sdFile.content);
  const current = sd.current ?? {};

  // Tokens + brand identity → current.*
  Object.assign(current, brand.tokens);
  current.brand_name    = brand.brand_name;
  current.brand_tagline = brand.brand_tagline;

  // Section settings
  const sections = current.sections ?? {};

  // hero (schema matches sections/hero.liquid)
  sections.hero = {
    type: "hero",
    settings: {
      eyebrow:    brand.hero.eyebrow    ?? "",
      headline:   brand.hero.headline,
      subhead:    brand.hero.subhead,
      cta_label:  brand.hero.cta_label,
      cta_link:   brand.hero.cta_link,
      cta2_label: brand.hero.cta2_label ?? "",
      cta2_link:  brand.hero.cta2_link  ?? "",
      image:      "",
    },
  };

  // featured-products
  const fp = brand.sections.featured_products ?? {};
  const staticBlocks: Record<string, { type: string; settings: Record<string, unknown> }> = {};
  const staticBlockOrder: string[] = [];

  (identity.products ?? []).slice(0, 12).forEach((p, idx) => {
    const id = `sp_${idx}`;
    staticBlocks[id] = {
      type: "static_product",
      settings: {
        title:         p.name,
        description:   p.description ?? "",
        price:         `${p.currency ?? "$"}${p.price}`,
        compare_price: "",
        image:         "",
        image_url:     p.images?.[0] ?? "",
        link:          `/products/${toHandle(p.name)}`,
      },
    };
    staticBlockOrder.push(id);
  });

  sections["featured-products"] = {
    type: "featured-products",
    settings: {
      heading:            fp.heading    ?? "This week's picks",
      subheading:         fp.subheading ?? "",
      collection:         "all",
      products_per_row:   3,
      products_per_page:  6,
      show_vendor:        false,
      cta_label:          fp.cta_label  ?? "Browse all",
      cta_link:           fp.cta_link   ?? "/collections/all",
    },
    blocks:      staticBlocks,
    block_order: staticBlockOrder,
  };

  // feature-grid
  if (brand.sections.feature_grid) {
    const fg = brand.sections.feature_grid;
    const blocks: Record<string, { type: string; settings: Record<string, unknown> }> = {};
    const order: string[] = [];
    fg.blocks.slice(0, 8).forEach((b, idx) => {
      const id = `f_${idx}`;
      blocks[id] = {
        type: "feature",
        settings: { icon: b.icon ?? "star", heading: b.heading, body: b.body },
      };
      order.push(id);
    });
    sections["feature-grid"] = {
      type: "feature-grid",
      settings: { heading: fg.heading, subheading: fg.subheading ?? "" },
      blocks,
      block_order: order,
    };
  }

  // testimonials
  if (brand.sections.testimonials) {
    const t = brand.sections.testimonials;
    const blocks: Record<string, { type: string; settings: Record<string, unknown> }> = {};
    const order: string[] = [];
    t.blocks.slice(0, 9).forEach((b, idx) => {
      const id = `t_${idx}`;
      blocks[id] = {
        type: "testimonial",
        settings: { quote: b.quote, author: b.author, role: b.role ?? "" },
      };
      order.push(id);
    });
    sections["testimonials"] = {
      type: "testimonials",
      settings: { heading: t.heading, subheading: t.subheading ?? "" },
      blocks,
      block_order: order,
    };
  }

  // faq
  if (brand.sections.faq) {
    const q = brand.sections.faq;
    const blocks: Record<string, { type: string; settings: Record<string, unknown> }> = {};
    const order: string[] = [];
    q.blocks.slice(0, 20).forEach((b, idx) => {
      const id = `q_${idx}`;
      blocks[id] = {
        type: "item",
        settings: { question: b.question, answer: b.answer },
      };
      order.push(id);
    });
    sections["faq"] = {
      type: "faq",
      settings: { heading: q.heading, subheading: q.subheading ?? "" },
      blocks,
      block_order: order,
    };
  }

  // cta
  if (brand.sections.cta) {
    sections["cta"] = {
      type: "cta",
      settings: {
        heading:   brand.sections.cta.heading,
        subhead:   brand.sections.cta.subhead ?? "",
        cta_label: brand.sections.cta.cta_label,
        cta_link:  brand.sections.cta.cta_link,
      },
    };
  }

  current.sections          = sections;
  current.content_for_index = brand.content_for_index;
  sd.current                = current;

  byPath.set(sdPath, {
    filePath: sdPath,
    content:  JSON.stringify(sd, null, 2) + "\n",
    language: "json",
  });

  // brand.css overwrite
  const brandCssPath = "assets/brand.css";
  byPath.set(brandCssPath, {
    filePath: brandCssPath,
    content:  brand.brand_css.endsWith("\n") ? brand.brand_css : brand.brand_css + "\n",
    language: "css",
  });

  // Also drive templates/index.json's hero + featured-products settings
  // so the homepage sections reference brand copy even when a merchant
  // resets via theme editor. (Shopify merges `settings_data.json`
  // sections with the template's `sections` by id — we update both.)
  const idxPath = "templates/index.json";
  const idxFile = byPath.get(idxPath);
  if (idxFile) {
    const idx = JSON.parse(idxFile.content);
    if (idx.sections?.hero)              idx.sections.hero.settings              = sections.hero.settings;
    if (idx.sections?.["featured-products"]) {
      idx.sections["featured-products"].settings   = sections["featured-products"].settings;
      idx.sections["featured-products"].blocks     = sections["featured-products"].blocks;
      idx.sections["featured-products"].block_order = sections["featured-products"].block_order;
    }
    if (idx.sections?.["feature-grid"] && sections["feature-grid"]) {
      idx.sections["feature-grid"] = sections["feature-grid"];
    }
    if (idx.sections?.testimonials     && sections.testimonials)     idx.sections.testimonials = sections.testimonials;
    if (idx.sections?.faq              && sections.faq)              idx.sections.faq          = sections.faq;
    if (idx.sections?.cta              && sections.cta)              idx.sections.cta          = sections.cta;
    idx.order = brand.content_for_index;

    byPath.set(idxPath, {
      filePath: idxPath,
      content:  JSON.stringify(idx, null, 2) + "\n",
      language: "json",
    });
  }

  return Array.from(byPath.values());
}

/* ------------------------------------------------------------------ *
 * Main entry: generateShopifyBundle                                   *
 * ------------------------------------------------------------------ */

const BRAND_LAYER_MAX_TOKENS = 6_000;
const MAX_ATTEMPTS           = 2;

export async function generateShopifyBundle(
  projectId: string,
  agencyId: string,
): Promise<{ filesCreated: number }> {
  const project = await Project.findOne({ _id: projectId, agencyId });
  if (!project) throw new Error("Project not found");
  if (!project.identity) throw new Error("Project has no identity — run extraction first");

  const identity = project.identity as IProjectIdentity;
  const promptProducts = productsForPrompt(identity);

  const direction = pickDesignDirection({
    tone:         identity.tone,
    industry:     identity.industry,
    businessName: identity.businessName,
    city:         identity.city,
    hasProducts:  Boolean(identity.products?.length),
  });
  log(`   ↳ design direction: ${direction.key} — "${direction.label}"`);

  const chooser = project.heroChooser as IHeroChooser | undefined;
  const lockedHero: string | undefined =
    chooser?.pickedVariantId && chooser?.variants?.length
      ? chooser.variants.find((v: IHeroVariant) => v.id === chooser.pickedVariantId)?.html
      : undefined;
  if (lockedHero) {
    log(`   ↳ locked hero: ${chooser?.pickedVariantId} (${lockedHero.length} chars)`);
  }

  // Load the scaffold eagerly — if this fails, there's no point calling
  // the AI.
  let scaffold: ScaffoldFile[];
  try {
    scaffold = await loadScaffold();
  } catch (err) {
    logError(`Failed to load Shopify scaffold at ${SCAFFOLD_DIR}`, err);
    throw new Error(`Shopify scaffold missing or unreadable at ${SCAFFOLD_DIR}: ${(err as Error).message}`);
  }
  log(`   ↳ loaded Shopify scaffold: ${scaffold.length} files`);

  // Expected file count for UI progress: scaffold + README + optional csv.
  const baseExpected = scaffold.length + 1 + (identity.products?.length ? 1 : 0);

  await Project.findByIdAndUpdate(projectId, {
    buildJobStatus:  "running",
    buildPhase:      "analyzing",
    buildFilesDone:  0,
    buildFilesTotal: baseExpected,
    buildError:      null,
    buildStartedAt:  new Date(),
    buildAttempt:    0,
    buildAttemptMax: MAX_ATTEMPTS,
  });

  const session = await AISession.create({
    agencyId,
    projectId,
    phase:  "generating",
    status: "active",
  });
  const sessionId = session._id;

  const identitySummary = {
    brandName: identity.businessName,
    tagline:   identity.tagline,
    industry:  identity.industry,
    tone:      identity.tone,
  };

  const basePrompt = getGenerateShopifyBrandPrompt({
    identity:   identitySummary,
    products:   promptProducts,
    direction,
    lockedHero,
  });

  const userContent =
    "## Task\n\n" +
    "Emit the brand-layer JSON for this store. JSON only. Begin with `{`.\n";

  log(
    `🛍  Generating Shopify brand layer for project ${projectId} ` +
    `(${identity.businessName}${promptProducts.length ? `, ${promptProducts.length} products` : ""})`,
  );

  let brand: BrandJson | null = null;
  let lastRaw = "";
  let lastIssues: PatchShopifyBrandIssue[] = [];

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    await Project.findByIdAndUpdate(projectId, {
      buildPhase:   attempt === 1 ? "generating" : "patching",
      buildAttempt: attempt,
    });

    const systemPrompt =
      attempt === 1
        ? basePrompt
        : getPatchShopifyBrandPrompt({
            identity:     identitySummary,
            direction,
            lockedHero,
            previousJson: lastRaw,
            issues:       lastIssues,
          });

    let text: string;
    try {
      const res = await analyzeOnce(systemPrompt, userContent, {
        phase:     "generating",
        maxTokens: BRAND_LAYER_MAX_TOKENS,
      });
      text = res.text;
      await trackUsage(sessionId.toString(), res.usage);
    } catch (err) {
      logError(`Shopify brand-layer AI call failed (attempt ${attempt})`, err);
      await Project.findByIdAndUpdate(projectId, {
        buildJobStatus: "failed",
        buildPhase:     "failed",
        buildError:     (err as Error).message,
      });
      await AISession.findByIdAndUpdate(sessionId, { phase: "failed", status: "failed", error: (err as Error).message });
      throw err;
    }

    lastRaw = text;
    const parseResult = tryParseBrandJson(text);
    if (!parseResult.ok) {
      lastIssues = [{
        path:    "(root)",
        issue:   `Previous output failed JSON.parse: ${parseResult.error}`,
        suggest: "Return ONLY a JSON object, no prose, no markdown fences",
      }];
      log(`⚠️  Shopify brand-layer attempt ${attempt}/${MAX_ATTEMPTS}: JSON parse failed — ${parseResult.error}`);
      continue;
    }

    const issues = validateBrandJson(parseResult.value);
    if (issues.length === 0) {
      brand = parseResult.value;
      log(`✅ Shopify brand-layer attempt ${attempt}/${MAX_ATTEMPTS}: validated`);
      break;
    }

    lastIssues = issues;
    log(
      `⚠️  Shopify brand-layer attempt ${attempt}/${MAX_ATTEMPTS}: ${issues.length} issue(s) — ` +
      issues.slice(0, 3).map((i) => i.path).join(", ") +
      (issues.length > 3 ? `, …+${issues.length - 3}` : ""),
    );
  }

  if (!brand) {
    const msg =
      `Shopify brand-layer JSON failed validation after ${MAX_ATTEMPTS} attempts.\n` +
      `Last issues: ${lastIssues.map((i) => `${i.path}: ${i.issue}`).join("; ")}`;
    await Project.findByIdAndUpdate(projectId, {
      buildJobStatus: "failed",
      buildPhase:     "failed",
      buildError:     msg,
    });
    await AISession.findByIdAndUpdate(sessionId, { phase: "failed", status: "failed", error: msg });
    throw new Error(msg);
  }

  // Merge brand layer into the scaffold, deterministically.
  await Project.findByIdAndUpdate(projectId, { buildPhase: "packaging" });
  const themed = applyBrandLayer(scaffold, brand, identity);

  // Wipe previous artifacts for this project.
  await GeneratedArtifact.deleteMany({ agencyId, projectId });

  const allFiles: ScaffoldFile[] = themed.map((f) => ({
    ...f,
    filePath: `theme/${f.filePath}`,
  }));

  // Top-level README (outside the theme/ subdir).
  allFiles.unshift({
    filePath: "README.txt",
    content:
      `Yappaflow → Shopify one-click bundle\n` +
      `====================================\n\n` +
      `1) Theme upload (one click, no re-zipping needed)\n` +
      `   • Shopify Admin → Online Store → Themes → "Upload zip file".\n` +
      `   • Select: shopify-theme.zip  (already packaged the way Shopify expects).\n` +
      `   • Click "Publish" once the upload finishes.\n\n` +
      (identity.products?.length
        ? `2) Product import\n` +
          `   • In Shopify Admin: Products → Import.\n` +
          `   • Select: products.csv\n` +
          `   • Confirm — Shopify will create products with variants and images.\n\n`
        : `2) Products\n` +
          `   • The theme ships empty. Add products in Shopify Admin → Products → Add product.\n\n`) +
      `Tip: Want us to do this automatically instead? Connect your Shopify store in\n` +
      `Yappaflow — we'll push the theme + products straight into your admin.\n\n` +
      `Generated by Yappaflow on ${new Date().toISOString()}.\n`,
    language: "text",
  });

  if (identity.products?.length) {
    allFiles.push({
      filePath: "products.csv",
      content:  buildProductsCsv(identity, identity.products),
      language: "csv",
    });
  }

  // Reclassify language for prefixed paths (defensive).
  for (const f of allFiles) f.language = languageForPath(f.filePath);

  for (const f of allFiles) {
    await GeneratedArtifact.create({
      agencyId,
      sessionId,
      projectId,
      filePath: f.filePath,
      content:  f.content,
      language: f.language,
      platform: "shopify",
      purpose:
        f.filePath === "products.csv" ? "shopify-products-csv" :
        f.filePath === "README.txt"   ? "shopify-readme" :
                                        "shopify-theme",
      version: 1,
    });
    await Project.findByIdAndUpdate(projectId, { $inc: { buildFilesDone: 1 } });
  }

  await Project.findByIdAndUpdate(projectId, {
    buildJobStatus:  "done",
    buildPhase:      "done",
    buildFilesTotal: allFiles.length,
    progress:        80,
  });
  await AISession.findByIdAndUpdate(sessionId, { phase: "ready", status: "completed" });

  log(`   → Generated ${allFiles.length} Shopify files for project ${projectId}`);
  return { filesCreated: allFiles.length };
}
